### ISSUE TITLE
API Key is not working

### ISSUE THREAD

**Issue by Manish-Bannur** [sagarsrao/NewsByjus#1]
401 Unauthorized https://newsapi.org/v2/top-headlines?country=us&apiKey=7bdb877e09764cb0b567c993b21f0680 (2596ms)

Response --> {"status":"error","code":"apiKeyInvalid","message":"Your API key is invalid or incorrect. Check your key, or go to https://newsapi.org to create a free API key."}

@sagarsrao

**Comment by sagarsrao** [comment]
Thanks for commenting out.

Please find the new API key:
cf808ef7895a403a96a790089d34119c

And the corresponding ex for that is shown below:
https://newsapi.org/v2/top-headlines?country=us&apiKey=cf808ef7895a403a96a790089d34119c

**Comment by ChidiogoVictor** [comment]
I'm getting this error bellow, please help. 
{'status': 'error', 'code': 'apiKeyInvalid', 'message': 'Your API key is invalid or incorrect. Check your key, or go to https://newsapi.org to create a free API key.'}

**Comment by ChidiogoVictor** [comment]
My API key is correct but invalid, pls how do i generate another working API, i need help. 
{'status': 'error', 'code': 'apiKeyInvalid', 'message': 'Your API key is invalid or incorrect. Check your key, or go to https://newsapi.org to create a free API key.'}
